# Rsyslog script: Logstash Dockerfile
# Rsyslog build version: 1.0
# Rsyslog Elastic Stack version: 7.1.1

FROM docker.elastic.co/logstash/logstash:7.1.1
LABEL description="Dockerfile base for Logstash"