# Rsyslog script: Elasticsearch Dockerfile
# Rsyslog build version: 1.0
# Rsyslog Elastic Stack version: 7.1.1

FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1
LABEL description="Dockerfile base for Elasticsearch"